version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: uptimefox-api
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///uptime.db

  worker:
    build: .
    container_name: uptimefox-worker
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///uptime.db

  beat:
    build: .
    container_name: uptimefox-beat
    command: celery -A celery_worker.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///uptime.db
